<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\EmployeeIdentity;
use App\Models\EmployeeAddress;
use App\Models\EmployeeEmergencyContact;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'employee' => [
                    'employee_code' => 'P680045',
                    'prefix' => 'นาย',
                    'first_name_th' => 'นนทิวัฒน์',
                    'last_name_th' => 'เพ็งพันธ์',
                    'first_name_en' => 'Nonthiwaht',
                    'last_name_en' => 'Pengpan',
                    'nickname' => 'นนท์',
                    'position' => 'Programmer',
                    'phone' => '0841566231',
                    'email' => 'nonthiwaht123@gmail.com',
                    'birth_date' => '2002-08-19',
                    'blood_group' => 'B',
                    'medical_condition' => null,
                    'hired_date' => '2025-06-23',
                ],
                'identity' => [
                    'id_card_number' => '0123456789012',
                    'passport_number' => 'AA1234567',
                    'pink_card_number' => null,
                    'work_permit_number' => 'WP2566012345',
                    'ssn' => '1234567890123',
                    'ssn_hospital' => 'โรงพยาบาลพีเอ็มจี',
                ],
                'address' => [
                    'house_no' => '33',
                    'moo' => '3',
                    'village_name' => null,
                    'soi' => null,
                    'road' => null,
                    'sub_district' => 'หนองปรง',
                    'district' => 'เขาย้อย',
                    'province' => 'เพชรบุรี',
                    'zipcode' => '76140',
                ],
                'emergency' => [
                    'name' => 'ลิโอเนล เมสซี',
                    'relationship' => 'นิดา',
                    'phone' => '0812345678',
                    'full_address' => '33 ม.3 ต.หนองปรง อ.เขาย้อย จ.เพชรบุรี 76140',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680050',
                    'prefix' => 'นางสาว',
                    'first_name_th' => 'สุธาทิพย์',
                    'last_name_th' => 'เนียมสุวรรณ',
                    'first_name_en' => 'Suthathip',
                    'last_name_en' => 'Niamsuwan',
                    'nickname' => 'แนน',
                    'position' => 'I/O & Warehouse',
                    'phone' => '0934747322',
                    'email' => 'suthathip@gmail.com',
                    'birth_date' => '2000-05-01',
                    'blood_group' => 'A',
                    'medical_condition' => 'แพ้ยาเพนิซิลิน',
                    'hired_date' => '2025-07-07',
                ],
                'identity' => [
                    'id_card_number' => '9876543210123',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '9876543210123',
                    'ssn_hospital' => 'โรงพยาบาลกรุงเทพ',
                ],
                'address' => [
                    'house_no' => '12',
                    'moo' => '5',
                    'village_name' => 'หมู่บ้านสุขใจ',
                    'soi' => null,
                    'road' => 'ถนนสุขุมวิท',
                    'sub_district' => 'บางนา',
                    'district' => 'บางนา',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10260',
                ],
                'emergency' => [
                    'name' => 'สมชาย เนียมสุวรรณ',
                    'relationship' => 'พ่อ',
                    'phone' => '0823456789',
                    'full_address' => '12 ม.5 ต.บางนา อ.บางนา จ.กรุงเทพมหานคร 10260',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680051',
                    'prefix' => 'นาย',
                    'first_name_th' => 'สมชาย',
                    'last_name_th' => 'ใจดี',
                    'first_name_en' => 'Somchai',
                    'last_name_en' => 'Jaidee',
                    'nickname' => 'ชาย',
                    'position' => 'IT Support',
                    'phone' => '0812345678',
                    'email' => 'somchai@gmail.com',
                    'birth_date' => '1998-03-15',
                    'blood_group' => 'O',
                    'medical_condition' => null,
                    'hired_date' => '2025-08-10',
                ],
                'identity' => [
                    'id_card_number' => '1234567890123',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '1234567890124',
                    'ssn_hospital' => 'โรงพยาบาลรามาธิบดี',
                ],
                'address' => [
                    'house_no' => '88',
                    'moo' => '2',
                    'village_name' => null,
                    'soi' => 'สาย 3',
                    'road' => 'ถนนพระราม 2',
                    'sub_district' => 'บางมด',
                    'district' => 'ทุ่งครุ',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10140',
                ],
                'emergency' => [
                    'name' => 'สมศรี ใจดี',
                    'relationship' => 'แม่',
                    'phone' => '0898765432',
                    'full_address' => '88 ม.2 ซ.สาย3 ถ.พระราม2 ต.บางมด อ.ทุ่งครุ กทม. 10140',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680052',
                    'prefix' => 'นางสาว',
                    'first_name_th' => 'สมหญิง',
                    'last_name_th' => 'รักดี',
                    'first_name_en' => 'Somying',
                    'last_name_en' => 'Rakdee',
                    'nickname' => 'หญิง',
                    'position' => 'HR Specialist',
                    'phone' => '0823456789',
                    'email' => 'somying@gmail.com',
                    'birth_date' => '1999-07-20',
                    'blood_group' => 'AB',
                    'medical_condition' => 'โรคหอบหืด',
                    'hired_date' => '2025-08-15',
                ],
                'identity' => [
                    'id_card_number' => '2345678901234',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '2345678901234',
                    'ssn_hospital' => 'โรงพยาบาลสมิติเวช',
                ],
                'address' => [
                    'house_no' => '45',
                    'moo' => '1',
                    'village_name' => 'หมู่บ้านร่มไทร',
                    'soi' => null,
                    'road' => 'ถนนลาดพร้าว',
                    'sub_district' => 'ลาดพร้าว',
                    'district' => 'ลาดพร้าว',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10230',
                ],
                'emergency' => [
                    'name' => 'สมศักดิ์ รักดี',
                    'relationship' => 'พ่อ',
                    'phone' => '0834567890',
                    'full_address' => '45 ม.1 ถ.ลาดพร้าว ต.ลาดพร้าว อ.ลาดพร้าว กทม. 10230',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680053',
                    'prefix' => 'นาย',
                    'first_name_th' => 'วีระชัย',
                    'last_name_th' => 'มั่นคง',
                    'first_name_en' => 'Weerachai',
                    'last_name_en' => 'Munkong',
                    'nickname' => 'วีร์',
                    'position' => 'Programmer',
                    'phone' => '0834567890',
                    'email' => 'weerachai@gmail.com',
                    'birth_date' => '2001-11-30',
                    'blood_group' => 'B',
                    'medical_condition' => null,
                    'hired_date' => '2025-09-01',
                ],
                'identity' => [
                    'id_card_number' => '3456789012345',
                    'passport_number' => 'BB2345678',
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '3456789012345',
                    'ssn_hospital' => 'โรงพยาบาลพระมงกุฎ',
                ],
                'address' => [
                    'house_no' => '22',
                    'moo' => '4',
                    'village_name' => null,
                    'soi' => 'สาย 7',
                    'road' => 'ถนนรัชดาภิเษก',
                    'sub_district' => 'ดินแดง',
                    'district' => 'ดินแดง',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10400',
                ],
                'emergency' => [
                    'name' => 'วีรา มั่นคง',
                    'relationship' => 'แม่',
                    'phone' => '0845678901',
                    'full_address' => '22 ม.4 ซ.สาย7 ถ.รัชดาภิเษก ต.ดินแดง อ.ดินแดง กทม. 10400',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680054',
                    'prefix' => 'นางสาว',
                    'first_name_th' => 'ดาริน',
                    'last_name_th' => 'แสงทอง',
                    'first_name_en' => 'Darin',
                    'last_name_en' => 'Sangtong',
                    'nickname' => 'ดา',
                    'position' => 'System Analyst',
                    'phone' => '0845678901',
                    'email' => 'darin@gmail.com',
                    'birth_date' => '1997-04-12',
                    'blood_group' => 'A',
                    'medical_condition' => 'แพ้อาหารทะเล',
                    'hired_date' => '2025-09-10',
                ],
                'identity' => [
                    'id_card_number' => '4567890123456',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '4567890123456',
                    'ssn_hospital' => 'โรงพยาบาลจุฬาลงกรณ์',
                ],
                'address' => [
                    'house_no' => '77',
                    'moo' => '6',
                    'village_name' => 'หมู่บ้านสวนทอง',
                    'soi' => null,
                    'road' => 'ถนนสีลม',
                    'sub_district' => 'สีลม',
                    'district' => 'บางรัก',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10500',
                ],
                'emergency' => [
                    'name' => 'ดารา แสงทอง',
                    'relationship' => 'พี่สาว',
                    'phone' => '0856789012',
                    'full_address' => '77 ม.6 ถ.สีลม ต.สีลม อ.บางรัก กทม. 10500',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680055',
                    'prefix' => 'นาย',
                    'first_name_th' => 'ชัยวัฒน์',
                    'last_name_th' => 'รุ่งเรือง',
                    'first_name_en' => 'Chaiwat',
                    'last_name_en' => 'Rungruang',
                    'nickname' => 'ชัย',
                    'position' => 'Database Admin',
                    'phone' => '0856789012',
                    'email' => 'chaiwat@gmail.com',
                    'birth_date' => '1996-09-25',
                    'blood_group' => 'O',
                    'medical_condition' => null,
                    'hired_date' => '2025-09-15',
                ],
                'identity' => [
                    'id_card_number' => '5678901234567',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '5678901234567',
                    'ssn_hospital' => 'โรงพยาบาลศิริราช',
                ],
                'address' => [
                    'house_no' => '15',
                    'moo' => '2',
                    'village_name' => null,
                    'soi' => 'สาย 1',
                    'road' => 'ถนนพระราม 4',
                    'sub_district' => 'คลองเตย',
                    'district' => 'คลองเตย',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10110',
                ],
                'emergency' => [
                    'name' => 'ชนิดา รุ่งเรือง',
                    'relationship' => 'ภรรยา',
                    'phone' => '0867890123',
                    'full_address' => '15 ม.2 ซ.สาย1 ถ.พระราม4 ต.คลองเตย อ.คลองเตย กทม. 10110',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680056',
                    'prefix' => 'นางสาว',
                    'first_name_th' => 'วิภาวี',
                    'last_name_th' => 'ใจเย็น',
                    'first_name_en' => 'Wipawee',
                    'last_name_en' => 'Jaiyen',
                    'nickname' => 'วิ',
                    'position' => 'UX/UI Designer',
                    'phone' => '0867890123',
                    'email' => 'wipawee@gmail.com',
                    'birth_date' => '2000-12-08',
                    'blood_group' => 'AB',
                    'medical_condition' => null,
                    'hired_date' => '2025-10-01',
                ],
                'identity' => [
                    'id_card_number' => '6789012345678',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '6789012345678',
                    'ssn_hospital' => 'โรงพยาบาลเวชศาสตร์เขตร้อน',
                ],
                'address' => [
                    'house_no' => '55',
                    'moo' => '3',
                    'village_name' => 'หมู่บ้านชวนชื่น',
                    'soi' => null,
                    'road' => 'ถนนนวมินทร์',
                    'sub_district' => 'นวมินทร์',
                    'district' => 'บึงกุ่ม',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10230',
                ],
                'emergency' => [
                    'name' => 'วิไล ใจเย็น',
                    'relationship' => 'แม่',
                    'phone' => '0878901234',
                    'full_address' => '55 ม.3 ถ.นวมินทร์ ต.นวมินทร์ อ.บึงกุ่ม กทม. 10230',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680057',
                    'prefix' => 'นาย',
                    'first_name_th' => 'ณัฐพล',
                    'last_name_th' => 'พงษ์ศักดิ์',
                    'first_name_en' => 'Natthaphon',
                    'last_name_en' => 'Phongsak',
                    'nickname' => 'ณัฐ',
                    'position' => 'QA Engineer',
                    'phone' => '0878901234',
                    'email' => 'natthaphon@gmail.com',
                    'birth_date' => '1999-02-14',
                    'blood_group' => 'B',
                    'medical_condition' => null,
                    'hired_date' => '2025-10-05',
                ],
                'identity' => [
                    'id_card_number' => '7890123456789',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '7890123456789',
                    'ssn_hospital' => 'โรงพยาบาลนครธน',
                ],
                'address' => [
                    'house_no' => '100',
                    'moo' => '7',
                    'village_name' => null,
                    'soi' => 'สาย 5',
                    'road' => 'ถนนบางนา-ตราด',
                    'sub_district' => 'บางนา',
                    'district' => 'บางนา',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10260',
                ],
                'emergency' => [
                    'name' => 'ณัฐนรี พงษ์ศักดิ์',
                    'relationship' => 'พี่สาว',
                    'phone' => '0889012345',
                    'full_address' => '100 ม.7 ซ.สาย5 ถ.บางนา-ตราด ต.บางนา อ.บางนา กทม. 10260',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680058',
                    'prefix' => 'นางสาว',
                    'first_name_th' => 'อรทัย',
                    'last_name_th' => 'บุญมี',
                    'first_name_en' => 'Orathai',
                    'last_name_en' => 'Bunmee',
                    'nickname' => 'อ้อ',
                    'position' => 'Project Manager',
                    'phone' => '0889012345',
                    'email' => 'orathai@gmail.com',
                    'birth_date' => '1995-06-30',
                    'blood_group' => 'A',
                    'medical_condition' => 'ความดันโลหิตสูง',
                    'hired_date' => '2025-10-10',
                ],
                'identity' => [
                    'id_card_number' => '8901234567890',
                    'passport_number' => 'CC3456789',
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '8901234567890',
                    'ssn_hospital' => 'โรงพยาบาลไทยนครินทร์',
                ],
                'address' => [
                    'house_no' => '30',
                    'moo' => '1',
                    'village_name' => 'หมู่บ้านธนาซิตี้',
                    'soi' => null,
                    'road' => 'ถนนบางนา-ตราด',
                    'sub_district' => 'บางโฉลง',
                    'district' => 'บางพลี',
                    'province' => 'สมุทรปราการ',
                    'zipcode' => '10540',
                ],
                'emergency' => [
                    'name' => 'บุญมา บุญมี',
                    'relationship' => 'สามี',
                    'phone' => '0890123456',
                    'full_address' => '30 ม.1 ถ.บางนา-ตราด ต.บางโฉลง อ.บางพลี จ.สมุทรปราการ 10540',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680059',
                    'prefix' => 'นาย',
                    'first_name_th' => 'สุรศักดิ์',
                    'last_name_th' => 'เก่งกาจ',
                    'first_name_en' => 'Surasak',
                    'last_name_en' => 'Kenggat',
                    'nickname' => 'เอก',
                    'position' => 'DevOps Engineer',
                    'phone' => '0890123456',
                    'email' => 'surasak@gmail.com',
                    'birth_date' => '1993-01-17',
                    'blood_group' => 'O',
                    'medical_condition' => null,
                    'hired_date' => '2025-10-15',
                ],
                'identity' => [
                    'id_card_number' => '9012345678901',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '9012345678901',
                    'ssn_hospital' => 'โรงพยาบาลสมุทรปราการ',
                ],
                'address' => [
                    'house_no' => '9',
                    'moo' => '5',
                    'village_name' => null,
                    'soi' => null,
                    'road' => 'ถนนสุขสวัสดิ์',
                    'sub_district' => 'ราษฎร์บูรณะ',
                    'district' => 'ราษฎร์บูรณะ',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10140',
                ],
                'emergency' => [
                    'name' => 'สุรีย์ เก่งกาจ',
                    'relationship' => 'แม่',
                    'phone' => '0901234567',
                    'full_address' => '9 ม.5 ถ.สุขสวัสดิ์ ต.ราษฎร์บูรณะ อ.ราษฎร์บูรณะ กทม. 10140',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680060',
                    'prefix' => 'นางสาว',
                    'first_name_th' => 'นิตยา',
                    'last_name_th' => 'ยิ้มแย้ม',
                    'first_name_en' => 'Nittaya',
                    'last_name_en' => 'Yimyam',
                    'nickname' => 'นิต',
                    'position' => 'Finance',
                    'phone' => '0901234567',
                    'email' => 'nittaya@gmail.com',
                    'birth_date' => '1998-08-22',
                    'blood_group' => 'B',
                    'medical_condition' => null,
                    'hired_date' => '2025-10-20',
                ],
                'identity' => [
                    'id_card_number' => '0123456789013',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '0123456789013',
                    'ssn_hospital' => 'โรงพยาบาลวิภาวดี',
                ],
                'address' => [
                    'house_no' => '66',
                    'moo' => '2',
                    'village_name' => 'หมู่บ้านเมืองทอง',
                    'soi' => null,
                    'road' => 'ถนนวิภาวดีรังสิต',
                    'sub_district' => 'ลาดยาว',
                    'district' => 'จตุจักร',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10900',
                ],
                'emergency' => [
                    'name' => 'นิรันดร์ ยิ้มแย้ม',
                    'relationship' => 'พ่อ',
                    'phone' => '0912345678',
                    'full_address' => '66 ม.2 ถ.วิภาวดีรังสิต ต.ลาดยาว อ.จตุจักร กทม. 10900',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680061',
                    'prefix' => 'นาย',
                    'first_name_th' => 'ศิริชัย',
                    'last_name_th' => 'พรหมจันทร์',
                    'first_name_en' => 'Sirichai',
                    'last_name_en' => 'Phromchan',
                    'nickname' => 'ศิริ',
                    'position' => 'Warehouse Manager',
                    'phone' => '0912345678',
                    'email' => 'sirichai@gmail.com',
                    'birth_date' => '1991-10-05',
                    'blood_group' => 'AB',
                    'medical_condition' => null,
                    'hired_date' => '2025-11-01',
                ],
                'identity' => [
                    'id_card_number' => '1234567890124',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '1234567890124',
                    'ssn_hospital' => 'โรงพยาบาลเปาโล',
                ],
                'address' => [
                    'house_no' => '18',
                    'moo' => '3',
                    'village_name' => null,
                    'soi' => 'สาย 2',
                    'road' => 'ถนนนิมิตใหม่',
                    'sub_district' => 'มีนบุรี',
                    'district' => 'มีนบุรี',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10510',
                ],
                'emergency' => [
                    'name' => 'ศิริพร พรหมจันทร์',
                    'relationship' => 'ภรรยา',
                    'phone' => '0923456789',
                    'full_address' => '18 ม.3 ซ.สาย2 ถ.นิมิตใหม่ ต.มีนบุรี อ.มีนบุรี กทม. 10510',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680062',
                    'prefix' => 'นางสาว',
                    'first_name_th' => 'กัญญารัตน์',
                    'last_name_th' => 'ศรีสุดา',
                    'first_name_en' => 'Kanyarat',
                    'last_name_en' => 'Srisuda',
                    'nickname' => 'กัญ',
                    'position' => 'Sales Executive',
                    'phone' => '0923456789',
                    'email' => 'kanyarat@gmail.com',
                    'birth_date' => '2001-03-28',
                    'blood_group' => 'A',
                    'medical_condition' => 'แพ้ยาซัลฟา',
                    'hired_date' => '2025-11-05',
                ],
                'identity' => [
                    'id_card_number' => '2345678901235',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '2345678901235',
                    'ssn_hospital' => 'โรงพยาบาลบางปะกอก',
                ],
                'address' => [
                    'house_no' => '44',
                    'moo' => '4',
                    'village_name' => 'หมู่บ้านลดาวัลย์',
                    'soi' => null,
                    'road' => 'ถนนพระราม 3',
                    'sub_district' => 'บางโพงพาง',
                    'district' => 'ยานนาวา',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10120',
                ],
                'emergency' => [
                    'name' => 'กัญจนา ศรีสุดา',
                    'relationship' => 'แม่',
                    'phone' => '0934567890',
                    'full_address' => '44 ม.4 ถ.พระราม3 ต.บางโพงพาง อ.ยานนาวา กทม. 10120',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680063',
                    'prefix' => 'นาย',
                    'first_name_th' => 'ธนากร',
                    'last_name_th' => 'สุขสันต์',
                    'first_name_en' => 'Thanakorn',
                    'last_name_en' => 'Suksan',
                    'nickname' => 'ตั้ม',
                    'position' => 'Marketing',
                    'phone' => '0934567890',
                    'email' => 'thanakorn@gmail.com',
                    'birth_date' => '2000-07-14',
                    'blood_group' => 'O',
                    'medical_condition' => null,
                    'hired_date' => '2025-11-10',
                ],
                'identity' => [
                    'id_card_number' => '3456789012346',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '3456789012346',
                    'ssn_hospital' => 'โรงพยาบาลธนบุรี',
                ],
                'address' => [
                    'house_no' => '7',
                    'moo' => '1',
                    'village_name' => null,
                    'soi' => 'สาย 9',
                    'road' => 'ถนนจรัญสนิทวงศ์',
                    'sub_district' => 'บางพลัด',
                    'district' => 'บางพลัด',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10700',
                ],
                'emergency' => [
                    'name' => 'ธนาภา สุขสันต์',
                    'relationship' => 'แม่',
                    'phone' => '0945678901',
                    'full_address' => '7 ม.1 ซ.สาย9 ถ.จรัญสนิทวงศ์ ต.บางพลัด อ.บางพลัด กทม. 10700',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680064',
                    'prefix' => 'นางสาว',
                    'first_name_th' => 'ปิยะนุช',
                    'last_name_th' => 'แก้วใส',
                    'first_name_en' => 'Piyanut',
                    'last_name_en' => 'Kaewsai',
                    'nickname' => 'นุช',
                    'position' => 'Accountant',
                    'phone' => '0945678901',
                    'email' => 'piyanut@gmail.com',
                    'birth_date' => '1997-12-01',
                    'blood_group' => 'B',
                    'medical_condition' => null,
                    'hired_date' => '2025-11-15',
                ],
                'identity' => [
                    'id_card_number' => '4567890123457',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '4567890123457',
                    'ssn_hospital' => 'โรงพยาบาลตากสิน',
                ],
                'address' => [
                    'house_no' => '25',
                    'moo' => '2',
                    'village_name' => 'หมู่บ้านพฤกษา',
                    'soi' => null,
                    'road' => 'ถนนสาทร',
                    'sub_district' => 'ทุ่งมหาเมฆ',
                    'district' => 'สาทร',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10120',
                ],
                'emergency' => [
                    'name' => 'ปิยะ แก้วใส',
                    'relationship' => 'พ่อ',
                    'phone' => '0956789012',
                    'full_address' => '25 ม.2 ถ.สาทร ต.ทุ่งมหาเมฆ อ.สาทร กทม. 10120',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680065',
                    'prefix' => 'นาย',
                    'first_name_th' => 'ประสิทธิ์',
                    'last_name_th' => 'ดีงาม',
                    'first_name_en' => 'Prasit',
                    'last_name_en' => 'Deengam',
                    'nickname' => 'สิทธิ์',
                    'position' => 'Network Engineer',
                    'phone' => '0956789012',
                    'email' => 'prasit@gmail.com',
                    'birth_date' => '1994-05-19',
                    'blood_group' => 'A',
                    'medical_condition' => null,
                    'hired_date' => '2025-11-20',
                ],
                'identity' => [
                    'id_card_number' => '5678901234568',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '5678901234568',
                    'ssn_hospital' => 'โรงพยาบาลกลาง',
                ],
                'address' => [
                    'house_no' => '3',
                    'moo' => '8',
                    'village_name' => null,
                    'soi' => null,
                    'road' => 'ถนนอโศก',
                    'sub_district' => 'คลองเตยเหนือ',
                    'district' => 'วัฒนา',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10110',
                ],
                'emergency' => [
                    'name' => 'ประไพ ดีงาม',
                    'relationship' => 'แม่',
                    'phone' => '0967890123',
                    'full_address' => '3 ม.8 ถ.อโศก ต.คลองเตยเหนือ อ.วัฒนา กทม. 10110',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680066',
                    'prefix' => 'นางสาว',
                    'first_name_th' => 'ภัทรา',
                    'last_name_th' => 'นิลสุวรรณ',
                    'first_name_en' => 'Phattra',
                    'last_name_en' => 'Nilsuwan',
                    'nickname' => 'ภัท',
                    'position' => 'HR Manager',
                    'phone' => '0967890123',
                    'email' => 'phattra@gmail.com',
                    'birth_date' => '1992-08-11',
                    'blood_group' => 'AB',
                    'medical_condition' => 'เบาหวาน',
                    'hired_date' => '2025-11-25',
                ],
                'identity' => [
                    'id_card_number' => '6789012345679',
                    'passport_number' => 'DD4567890',
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '6789012345679',
                    'ssn_hospital' => 'โรงพยาบาลบำรุงราษฎร์',
                ],
                'address' => [
                    'house_no' => '99',
                    'moo' => '6',
                    'village_name' => 'หมู่บ้านสวนหลวง',
                    'soi' => null,
                    'road' => 'ถนนสุขุมวิท',
                    'sub_district' => 'พระโขนง',
                    'district' => 'คลองเตย',
                    'province' => 'กรุงเทพมหานคร',
                    'zipcode' => '10260',
                ],
                'emergency' => [
                    'name' => 'ภาณุ นิลสุวรรณ',
                    'relationship' => 'สามี',
                    'phone' => '0978901234',
                    'full_address' => '99 ม.6 ถ.สุขุมวิท ต.พระโขนง อ.คลองเตย กทม. 10260',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680067',
                    'prefix' => 'นาย',
                    'first_name_th' => 'กิตติพงษ์',
                    'last_name_th' => 'ทองดี',
                    'first_name_en' => 'Kittiphong',
                    'last_name_en' => 'Thongdee',
                    'nickname' => 'กิต',
                    'position' => 'Security Officer',
                    'phone' => '0978901234',
                    'email' => 'kittiphong@gmail.com',
                    'birth_date' => '1990-11-23',
                    'blood_group' => 'O',
                    'medical_condition' => null,
                    'hired_date' => '2025-12-01',
                ],
                'identity' => [
                    'id_card_number' => '7890123456790',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '7890123456790',
                    'ssn_hospital' => 'โรงพยาบาลราษฎร์บูรณะ',
                ],
                'address' => [
                    'house_no' => '11',
                    'moo' => '4',
                    'village_name' => null,
                    'soi' => 'สาย 6',
                    'road' => 'ถนนพุทธมณฑล',
                    'sub_district' => 'ศาลายา',
                    'district' => 'พุทธมณฑล',
                    'province' => 'นครปฐม',
                    'zipcode' => '73170',
                ],
                'emergency' => [
                    'name' => 'กิตติยา ทองดี',
                    'relationship' => 'ภรรยา',
                    'phone' => '0989012345',
                    'full_address' => '11 ม.4 ซ.สาย6 ถ.พุทธมณฑล ต.ศาลายา อ.พุทธมณฑล จ.นครปฐม 73170',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680068',
                    'prefix' => 'นางสาว',
                    'first_name_th' => 'ชลธิชา',
                    'last_name_th' => 'พุ่มพวง',
                    'first_name_en' => 'Chonthicha',
                    'last_name_en' => 'Phumphuang',
                    'nickname' => 'ชล',
                    'position' => 'Receptionist',
                    'phone' => '0989012345',
                    'email' => 'chonthicha@gmail.com',
                    'birth_date' => '2003-04-06',
                    'blood_group' => 'A',
                    'medical_condition' => null,
                    'hired_date' => '2025-12-05',
                ],
                'identity' => [
                    'id_card_number' => '8901234567891',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '8901234567891',
                    'ssn_hospital' => 'โรงพยาบาลนนทบุรี',
                ],
                'address' => [
                    'house_no' => '50',
                    'moo' => '5',
                    'village_name' => 'หมู่บ้านเพชรงาม',
                    'soi' => null,
                    'road' => 'ถนนติวานนท์',
                    'sub_district' => 'บางกระสอ',
                    'district' => 'เมืองนนทบุรี',
                    'province' => 'นนทบุรี',
                    'zipcode' => '11000',
                ],
                'emergency' => [
                    'name' => 'ชลอ พุ่มพวง',
                    'relationship' => 'พ่อ',
                    'phone' => '0990123456',
                    'full_address' => '50 ม.5 ถ.ติวานนท์ ต.บางกระสอ อ.เมืองนนทบุรี จ.นนทบุรี 11000',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680069',
                    'prefix' => 'นาย',
                    'first_name_th' => 'ศราวุธ',
                    'last_name_th' => 'ขาวสะอาด',
                    'first_name_en' => 'Sarawut',
                    'last_name_en' => 'Khaosamaat',
                    'nickname' => 'วุธ',
                    'position' => 'Driver',
                    'phone' => '0990123456',
                    'email' => 'sarawut@gmail.com',
                    'birth_date' => '1988-09-15',
                    'blood_group' => 'B',
                    'medical_condition' => null,
                    'hired_date' => '2025-12-10',
                ],
                'identity' => [
                    'id_card_number' => '9012345678902',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '9012345678902',
                    'ssn_hospital' => 'โรงพยาบาลปทุมธานี',
                ],
                'address' => [
                    'house_no' => '6',
                    'moo' => '3',
                    'village_name' => null,
                    'soi' => null,
                    'road' => 'ถนนรังสิต-นครนายก',
                    'sub_district' => 'ประชาธิปัตย์',
                    'district' => 'ธัญบุรี',
                    'province' => 'ปทุมธานี',
                    'zipcode' => '12130',
                ],
                'emergency' => [
                    'name' => 'ศรีสุดา ขาวสะอาด',
                    'relationship' => 'ภรรยา',
                    'phone' => '0801234567',
                    'full_address' => '6 ม.3 ถ.รังสิต-นครนายก ต.ประชาธิปัตย์ อ.ธัญบุรี จ.ปทุมธานี 12130',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680070',
                    'prefix' => 'นางสาว',
                    'first_name_th' => 'มนัสนันท์',
                    'last_name_th' => 'เพ็ชรแสง',
                    'first_name_en' => 'Manasnan',
                    'last_name_en' => 'Phetsaeng',
                    'nickname' => 'มิ้น',
                    'position' => 'Purchasing',
                    'phone' => '0801234567',
                    'email' => 'manasnan@gmail.com',
                    'birth_date' => '2002-01-29',
                    'blood_group' => 'AB',
                    'medical_condition' => null,
                    'hired_date' => '2025-12-15',
                ],
                'identity' => [
                    'id_card_number' => '0123456789014',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '0123456789014',
                    'ssn_hospital' => 'โรงพยาบาลรังสิต',
                ],
                'address' => [
                    'house_no' => '38',
                    'moo' => '7',
                    'village_name' => 'หมู่บ้านฟ้าใส',
                    'soi' => null,
                    'road' => 'ถนนพหลโยธิน',
                    'sub_district' => 'คูคต',
                    'district' => 'ลำลูกกา',
                    'province' => 'ปทุมธานี',
                    'zipcode' => '12130',
                ],
                'emergency' => [
                    'name' => 'มนัส เพ็ชรแสง',
                    'relationship' => 'พ่อ',
                    'phone' => '0811234567',
                    'full_address' => '38 ม.7 ถ.พหลโยธิน ต.คูคต อ.ลำลูกกา จ.ปทุมธานี 12130',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680071',
                    'prefix' => 'นาย',
                    'first_name_th' => 'อภิชาติ',
                    'last_name_th' => 'สมบูรณ์',
                    'first_name_en' => 'Aphichat',
                    'last_name_en' => 'Somboon',
                    'nickname' => 'ชาติ',
                    'position' => 'Logistics',
                    'phone' => '0811234567',
                    'email' => 'aphichat@gmail.com',
                    'birth_date' => '1996-06-18',
                    'blood_group' => 'O',
                    'medical_condition' => null,
                    'hired_date' => '2025-12-20',
                ],
                'identity' => [
                    'id_card_number' => '1234567890125',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '1234567890125',
                    'ssn_hospital' => 'โรงพยาบาลสระบุรี',
                ],
                'address' => [
                    'house_no' => '20',
                    'moo' => '2',
                    'village_name' => null,
                    'soi' => 'สาย 4',
                    'road' => 'ถนนมิตรภาพ',
                    'sub_district' => 'ปากเพรียว',
                    'district' => 'เมืองสระบุรี',
                    'province' => 'สระบุรี',
                    'zipcode' => '18000',
                ],
                'emergency' => [
                    'name' => 'อภิญญา สมบูรณ์',
                    'relationship' => 'แม่',
                    'phone' => '0822345678',
                    'full_address' => '20 ม.2 ซ.สาย4 ถ.มิตรภาพ ต.ปากเพรียว อ.เมืองสระบุรี จ.สระบุรี 18000',
                ],
            ],
            [
                'employee' => [
                    'employee_code' => 'P680072',
                    'prefix' => 'นางสาว',
                    'first_name_th' => 'จิราพร',
                    'last_name_th' => 'วงค์สุวรรณ',
                    'first_name_en' => 'Jiraporn',
                    'last_name_en' => 'Wongsuwan',
                    'nickname' => 'จิ',
                    'position' => 'Customer Service',
                    'phone' => '0822345678',
                    'email' => 'jiraporn@gmail.com',
                    'birth_date' => '2001-10-10',
                    'blood_group' => 'A',
                    'medical_condition' => null,
                    'hired_date' => '2025-12-25',
                ],
                'identity' => [
                    'id_card_number' => '2345678901236',
                    'passport_number' => null,
                    'pink_card_number' => null,
                    'work_permit_number' => null,
                    'ssn' => '2345678901236',
                    'ssn_hospital' => 'โรงพยาบาลสระบุรี',
                ],
                'address' => [
                    'house_no' => '14',
                    'moo' => '1',
                    'village_name' => 'หมู่บ้านโชคดี',
                    'soi' => null,
                    'road' => 'ถนนสุดบรรทัด',
                    'sub_district' => 'หนองปลาไหล',
                    'district' => 'เมืองสระบุรี',
                    'province' => 'สระบุรี',
                    'zipcode' => '18000',
                ],
                'emergency' => [
                    'name' => 'จิรายุ วงค์สุวรรณ',
                    'relationship' => 'พ่อ',
                    'phone' => '0833456789',
                    'full_address' => '14 ม.1 ถ.สุดบรรทัด ต.หนองปลาไหล อ.เมืองสระบุรี จ.สระบุรี 18000',
                ],
            ],
        ];

        foreach ($employees as $data) {
            $emp = Employee::create($data['employee']);
            $emp->identity()->create($data['identity']);
            $emp->addresses()->create($data['address']);
            $emp->emergencyContacts()->create($data['emergency']);
        }
    }
}